### ISSUE TITLE
don't treat unmatched closing tags as text

### ISSUE THREAD

**Issue by lddubeau** [isaacs/sax-js#153]
### Versions

sax: 1.1.1
Node: 0.10.35 
(Yeah, I should upgrade)

### Steps to reproduce

Run this with the versions above:

```
var sax = require("sax"),
    parser = sax.parser(true);

parser.ontext = function (t) {
    console.log("ontext", t);
};

parser.onopentag = function (node) {
    console.log("onopentag", node);
};

parser.onend = function () {
    console.log("onend");
};

parser.write('<xml></foo></xml>').close();
```

### Actual results

```
onopentag { name: 'xml', attributes: {}, isSelfClosing: false }
ontext </foo>

/tmp/t4/node_modules/sax/lib/sax.js:926
  if (this.error) throw this.error
                            ^
Error: Unmatched closing tag: foo
Line: 0
Column: 11
Char: >
    at error (/tmp/t4/node_modules/sax/lib/sax.js:652:8)
    at strictFail (/tmp/t4/node_modules/sax/lib/sax.js:675:22)
    at closeTag (/tmp/t4/node_modules/sax/lib/sax.js:864:5)
    at Object.write (/tmp/t4/node_modules/sax/lib/sax.js:1314:29)
    at Object.<anonymous> (/tmp/t4/test.js:17:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

### Expected results

Same as the actual results, minus the line `ontext </foo>`

### Observations

The problem is in `closeTag`:

```
  if (t < 0) {
    strictFail(parser, "Unmatched closing tag: "+parser.tagName)
    parser.textNode += "</" + parser.tagName + ">"
    parser.state = S.TEXT
    return
  }
```

After the error is generated, the closing tag added to `parser.textNode` and is then going to be treated as text. I understand that the validation capabilities of sax are limited, but what benefit is there to having a closing tag be treated as text?

A system that validates XML and which is built on top of sax could decide to provide the user with the error message but continue processing the file as much as possible. However, having errant closing tags passed on as text to the code that uses `sax` throws a monkey wrench into this process.

**Comment by deepaknverma** [comment]
1+
