### ISSUE TITLE
Unbound namespace prefix: "sketch"

### ISSUE THREAD

**Issue by eliseumds** [isaacs/sax-js#173]
Hi guys, I just used *gulp-imagemin* and got the following exception:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: Unbound namespace prefix: "sketch"
    at error ($REPO/node_modules/sax/lib/sax.js:666:10)
    at strictFail ($REPO/node_modules/sax/lib/sax.js:692:7)
    at openTag ($REPO/node_modules/sax/lib/sax.js:824:11)
    at Object.write ($REPO/node_modules/sax/lib/sax.js:1300:13)
    at module.exports ($REPO/node_modules/svgo/lib/svgo/svg2js.js:144:9)
    at SVGO._optimizeOnce ($REPO/node_modules/svgo/lib/svgo.js:56:5)
    at SVGO.optimize ($REPO/node_modules/svgo/lib/svgo.js:48:11)
    at Through2._transform ($REPO/node_modules/imagemin-svgo/index.js:29:9)
    at Through2.Transform._read ($REPO/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at Through2.Transform._write ($REPO/node_modules/readable-stream/lib/_stream_transform.js:160:12)
```

Should *sax-js* cope with it or should I remove these attributes?

**Comment by isaacs** [comment]
Well, you're not really "supposed" to use namespaces that aren't bound to a URL.  Probably there's a `xmlns` that you need in the root (or some parent tag) to bind the namespace?

**Comment by LiamKarlMitchell** [comment]
Had similar issue with XML doc that did not have the namespace added.

I just added it manually to the parser
```
saxStream._parser.ns["dt"]="urn:schemas-microsoft-com:datatypes"
```
